### ISSUE TITLE
Can't delete an Offer that has invoices

### ISSUE THREAD

**Issue by freakinhuge** [dailydrip/exchequer-server#39]
When trying to delete an Offer from the ActiveAdmin interface, rails throws a foreign key relationship failure error due to the `app/models/offer.rb` not having a `has_many :invoices` relationship defined.

**Comment by loldlm1** [comment]
Even with the `has_many :invoices` relation fixed, we can't delete an offer because an Invoice `has_many :line_items, dependent: :nullify` and it isn't `dependent: :destroy`. I should add it?

**Comment by adamdill** [comment]
lets leave it without an option. I don't think we ever should destroy an invoice that has purchases associated with it, because then we are orphaning transactions and it will make any historical accounting research much more difficult.

**Comment by franzejr** [comment]
ping @freakinhuge

**Comment by freakinhuge** [comment]
Sounds good to me @adamdill @franzejr
