### ISSUE TITLE
Can't specify cents in checkout

### ISSUE THREAD

**Issue by freakinhuge** [dailydrip/exchequer-server#42]
When trying to checkout for a deferrable offer where you can specify the amount to pay, you can't specify cents as the `number_field_tag` needs a `step: :any` option added to it in [app/view/checkouts/_make_payment_form.html.haml:6](https://github.com/dailydrip/exchequer-server/blob/master/app/views/checkouts/_make_payment_form.html.haml#L6)

**Comment by loldlm1** [comment]
I've realized that we can't do this. According with the reference 8 in this article: https://blog.spreedly.com/2017/04/07/getting-started-with-spreedly-common-questions/ and the local tests that I've done, Spreedly just can receive an integer to its back-end, so we should keep passing an integer.
